name: Publish package

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Build, test, and publish to npm
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: '@programinglive'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish to npm
        run: npm publish --provenance --access public
